# Generated by Django 4.1.3 on 2022-11-02 20:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
